# <font color='blue'>Data Science Academy - Machine Learning</font>

# <font color='blue'>Capítulo 6 - Métodos Ensemble</font>

## Bagging

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.BaggingClassifier.html

In [1]:
# Import
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.datasets import load_digits
from sklearn.preprocessing import scale

In [2]:
# Carga de dados
digits = load_digits()

In [3]:
# Pré-processamento
data = scale(digits.data)

In [4]:
# Variáveis preditoras e variável target
X = data
y = digits.target

In [5]:
# Construção do Classificador
bagging = BaggingClassifier(KNeighborsClassifier(), max_samples = 0.5, max_features = 0.5)

In [6]:
bagging

BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
         bootstrap=True, bootstrap_features=False, max_features=0.5,
         max_samples=0.5, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=0, warm_start=False)

In [7]:
?cross_val_score

In [8]:
# Score do modelo
scores = cross_val_score(bagging, X, y)

In [9]:
# Média do score
mean = scores.mean()

In [10]:
print(scores)

[0.93023256 0.92654424 0.93456376]


In [11]:
print(mean)

0.9304468523098214


## Extremely Randomized Trees (ExtraTrees)

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.ExtraTreesClassifier.html

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html

In [12]:
# Import
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_digits
from sklearn.preprocessing import scale

In [13]:
# Carregando os dados
digits = load_digits()

In [14]:
# Pré-processamento
data = scale(digits.data)

In [15]:
# Variáveis preditoras e variável target
X = data
y = digits.target

In [16]:
# Cria o classificador
clf = DecisionTreeClassifier(max_depth = None, min_samples_split = 2, random_state = 0)
scores = cross_val_score(clf, X, y)
mean = scores.mean()
print(scores)
print(mean)

[0.73920266 0.8130217  0.76342282]
0.7718823931457729


In [17]:
clf = RandomForestClassifier(n_estimators = 10, max_depth = None, min_samples_split = 2, random_state = 0)
scores = cross_val_score(clf, X, y)
mean = scores.mean()
print(scores)
print(mean)

[0.90697674 0.89983306 0.90771812]
0.9048426400277451


In [18]:
clf = ExtraTreesClassifier(n_estimators = 10, max_depth = None, min_samples_split = 2, random_state = 0)
scores = cross_val_score(clf, X, y)
mean = scores.mean()
print(scores)
print(mean)

[0.89202658 0.90984975 0.91610738]
0.9059945700686877


## Adaboost

http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.AdaBoostClassifier.html

In [ ]:
# Import
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.datasets.mldata import fetch_mldata
from sklearn.model_selection import cross_val_score

In [ ]:
# Carregandos os dados
heart = fetch_mldata("heart")
X = heart.data
y = np.copy(heart.target)
y[y == -1] = 0

In [ ]:
# Datasets de treino e de teste
X_test, y_test = X[189:], y[189:]
X_train, y_train = X[:189], y[:189]

In [ ]:
# Construindo o estimador base
estim_base = DecisionTreeClassifier(max_depth = 1, min_samples_leaf = 1)
estim_base.fit(X_train, y_train)
estim_base_err = 1.0 - estim_base.score(X_test, y_test)

In [ ]:
ada_clf = AdaBoostClassifier(base_estimator = estim_base, 
                                  learning_rate = 1.0, 
                                  n_estimators = 400, 
                                  algorithm = "SAMME")

In [ ]:
ada_clf.fit(X_train, y_train)

In [ ]:
scores = cross_val_score(ada_clf, X_test, y_test)
print(scores)
means = scores.mean()
print(means)

### Fim

### Obrigado - Data Science Academy - <a href="http://facebook.com/dsacademybr">facebook.com/dsacademybr</a>